### ISSUE TITLE
Возвращаемые типы - ошибка c наследованием

### ISSUE THREAD

**Issue by TsSaltan** [jphp-group/jphp#259]
Если у класса родителя или у интерфейса, у метода явно не указан возвращаемый тип
```php
interface a {
   public function test();
}
```
а у класса, реализующего этот интерфейс, у того же метода указан тип:
```php
class b implements a {
   public function test() : array {
   }
}
```
то происходит ошибка
`
Fatal error: Uncaught Error: Declaration of b::test(): array must be compatible with a::test...
`
хотя по идее, этого не должно быть, т.к. у родителя явно не указан возвращаемый тип

**Comment by dim-s** [comment]
Просто в php 7.2 решили не падать ошибкой в таких случаях.

**Comment by TsSaltan** [comment]
php 7.1 тоже не падает

**Comment by dim-s** [comment]
fixed.
