### ISSUE TITLE
Некорректно работает генератор со ссылкой

### ISSUE THREAD

**Issue by TsSaltan** [jphp-group/jphp#262]
```php
function &gen() {
    $value = 5;

    while ($value > 0) {
        yield $value;
    }
}

foreach (gen() as &$a) {
    var_dump($a--);
}
```

Ожидается:
```
int(5) 
int(4) 
int(3) 
int(2) 
int(1)
```

Получаем бесконечный цикл ( int(5) ), т.к. переменная $value, переданная по ссылке, не меняет значение

**Comment by dim-s** [comment]
По-моему в jphp просто не реализованы ссылки для генераторов.

**Comment by dim-s** [comment]
Нет, оказывается просто баг. Пофиксено.
