### ISSUE TITLE
[JPPM] Не работает gradlew под linux

### ISSUE THREAD

**Issue by MWGuy** [jphp-group/jphp#265]
Не работает gradlew под linux. Но если установить под linux gradle и поменять gradlePlugin.php то всё работает. Можно сделать проверку на то что если есть gradle на ПК то использовать его. А если нет то уже gradlew

**Comment by MWGuy** [comment]
Скажу честно этот баг уже бесит. И за него я даже перестанавливал систему но без успешно :(

**Comment by dim-s** [comment]
Исправлено в 0.3.7
