### ISSUE TITLE
build fatjar

### ISSUE THREAD

**Issue by guangrei** [jphp-group/jphp#270]
hi, any guide to build fatjar distribution from jphp project?

**Comment by dim-s** [comment]
This is difficult to implement without changing the source code. To do this, you need to add a new subproject with all the project dependencies that are needed and connect something like shadowJar plugin for gradle (https://github.com/johnrengelman/shadow).

**Comment by dim-s** [comment]
What is the problem you are trying to solve in this way?

**Comment by guangrei** [comment]
I tried to make a single jar runnable from jphp projects

**Comment by dim-s** [comment]
Try this: https://github.com/jphp-group/jphp/tree/master/packager

It allows to build single jar from php sources with any extensions.

**Comment by guangrei** [comment]
thank you very much 🙏🏻
