### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by zakulqi** [jphp-group/jphp#292]
`class a{ public static $asd = ['q' => 'w']; }`
`$type = 'asd';`
`$rule = 'q';`
`var_dump(a::${$type}[$rule]);`

Fatal error: Uncaught ParseError: Syntax error, unexpected '[' on line 4

**Comment by MONAROL** [comment]
А так же

``$rule = 'q';
var_dump(
    (['q' => 'w'])[$rule]
);``

**Comment by MONAROL** [comment]
Так же не работает и такая конструкция

class a{ public static $asd = ['q' => 'w']; }
$type = 'asd';
$rule = 'q';
$f = fn() => a::$$type;
var_dump($f());

**Comment by MONAROL** [comment]
И ещё так

class a{ public static $asd = ['q' => 'w']; }
$type = 'asd';
$rule = 'q';
$f = function() use ($type) {return a::$$type; };
var_dump(($f)()[$rule]);

Но если убрать обворачивание ($f) -> $f то всё нормально

**Comment by MONAROL** [comment]
А вот на эту конструкцию ругается шторм, и она не работает в обычном пхп. Но в jphp работает.
но если обернуть `function(){}` в скобки -> `(function(){})`, то наоборот в обычном пхп работает а в jphp нет

![phpstorm-err](https://user-images.githubusercontent.com/38406949/52910944-c35f9e80-32af-11e9-953f-c3b5c9b7f834.png)

**Comment by MONAROL** [comment]
Так же unset не принимает референс от лямбды

`class a{ public static $asd = ['q' => 'w', 'merged' => ['a' => 'b', 'q' => 'w', 'c' => 'd']]; }`
`$type = 'asd';`
`$rule = 'q';`
`$f = function &() use ($type) {return a::$$type;};`
`unset(`
`    $f()['merged'][$rule]`
`);`
`var_dump(a::$$type);`

В обычном пхп всё работает.
