### ISSUE TITLE
Bug, input var changing without reference

### ISSUE THREAD

**Issue by zakulqi** [jphp-group/jphp#293]
```php
function test_except($arr, array $keys) {
	test_forget($arr, $keys);
	return $arr;
}
function test_forget(&$arr, array $keys) {
	foreach ($keys as $key) {
		unset($arr[$key]);
	}
}

$bindings = [
	'select' => [],
	'from' => [],
	'join' => [],
	'where' => [],
];

$clean = test_except($bindings, ['select', 'join']);

var_dump($clean, $bindings);
```

Изменяет значение в переменной bindings хотя она не была передана по ссылке
Можно решить добавив $arr = $arr; в начале test_except

**Comment by MONAROL** [comment]
Вот ещё пример, где проявляется баг

`class a{ public static $asd = ['q' => 'w', 'merged' => ['a' => 'b', 'q' => 'w', 'c' => 'd']]; }`
`$type = 'asd';`
`$rule = 'q';`
`$f = a::$$type;`
`unset(`
    $f['merged'][$rule]`
`);`
`var_dump(a::$$type);`
