### ISSUE TITLE
Bug with using traits

### ISSUE THREAD

**Issue by zakulqi** [jphp-group/jphp#294]
`class Builder`
`{`
`    use BuildsQueries, Macroable {`
`        __call as macroCall;`
`    }`
`}`
Ищет _call в BuildsQueries, а не Macroable

**Comment by dim-s** [comment]
@MONAROL Т.е. в оригинальном php поиск метода идет справа на лево, а в jphp слева на право.

**Comment by MONAROL** [comment]
@dim-s, тут про другое. Пытается найти метод __call в BuildsQueries, а не Macroable

**Comment by MONAROL** [comment]
@dim-s, Код:
`trait BuildsQueries{}`
`trait Macroable { function __call($a, $b) {} }`

`class Builder`
`{`
`use BuildsQueries, Macroable {`
`__call as macroCall;`
`}`
`}`
`echo 'ok';`

Выдаёт в jphp ошибку:
![image](https://user-images.githubusercontent.com/38406949/52914836-426bcb80-32de-11e9-8533-256f9220261a.png)
