### ISSUE TITLE
CaseInsensitiveMap from Commons Collection is out of date.

### ISSUE THREAD

**Issue by nstdio** [jphp-group/jphp#297]
I was playing around with the code and find out that `CaseInsensitiveMap<V>` is broken. In particular the `#containsKey(Object key)` method is case sensitive. I've try to dive deep into this issue and find out that in the latest version of Commons Collection it's fine. `#containsKey(Object key)` method gives the expected results, the key search is not case sensitive. That method is implemented in `AbstractHashedMap<K,V>`. There is no direct tests for that classes.

Currently I'm blocked by that issue.

**Comment by dim-s** [comment]
This class does not seem to be used in jphp core or runtime or any extension. The best solution is to remove it from the jphp source and use another class for your purpose.
