### ISSUE TITLE
strval.phpt: Output order.

### ISSUE THREAD

**Issue by nstdio** [jphp-group/jphp#301]
Please add this line at the beginning of `LangFunctions#strval` method, before return statement:

```java
        if (memory.isArray()) {
            env.notice(trace, "Array to string conversion");
        }
```
Please run [strval.phpt](https://github.com/php/php-src/blob/master/ext/standard/tests/strings/strval.phpt).

The actual result is:
```
Notice: Array to string conversion in 'strval.phpt' on line 11 at pos 10
string(3) "bar"
string(3) "BAR"
string(6) "foobar"
string(1) "1"
string(3) "1.1"
string(1) "1"
string(0) ""
string(5) "Array"
```

but if we replace last array with variable (not constant) or remove `@Immutable` annotation from `LangFunctions#strval` every thing works as expected except new line before notice message.

I could only guess that constant expression are evaluated earlier then expression that needs a runtime environment to compute their values. The notice message is written to output buffer earlier then everything else.
What does this `@Immutable` thing mean? It's sort of no side effect method?

BTW, there is no javadoc on `php.runtime.annotation` package annotations, please can you document them?

**Comment by dim-s** [comment]
If a function is marked as `@Immutable` the all calls of this function in bytecode will be genereated as direct calls via JVM CALL instructions. This summary allows you to greatly reduce the time spent on a function call.

**Comment by dim-s** [comment]
@Immutable can be removed in this case for php capability to the detriment of performance.

**Comment by dim-s** [comment]
Also immutable functions can be called in the compile time and its results can be inserted into bytecode instead of JVM Calls. This can happen if you pass constant values to the functions.

**Comment by nstdio** [comment]
> `@Immutable` can be removed in this case for php capability to the detriment of performance.

Don't you think this is the more so issue of incorrect strange behavior rather then PHP capability?

**Comment by dim-s** [comment]
We will not fix, because does not break backward compatibility at the code execution level.
