### ISSUE TITLE
Environment#current() is deprecated. What is replacement?

### ISSUE THREAD

**Issue by nstdio** [jphp-group/jphp#302]
The `Environment#current()` is deprecated. What is replacement or if replacement missing how we can get Environment in places where it not passed as parameter.

**Comment by dim-s** [comment]
There are two variants:

1. Pass as parameter
2. Keep a reference to an env object somewhere in your objects.

Environment#current() uses ThreadLocal to keep an env object, but it's not correct behaviour in some cases. If you are using `concurrent` environments for multitheareading you need only one environement object and you can create as many env objects not attached to threads.

**Comment by nstdio** [comment]
I see, very thanks. I was thinking there is a short easy way, but it's not documented. I think we should talk about this in concrete examples. Let's discuss this around the code. I've open a PR soon.
