### ISSUE TITLE
How can I get the file list 

### ISSUE THREAD

**Issue by xavieryang007** [jphp-group/jphp#319]
![image](https://user-images.githubusercontent.com/6174650/62518638-9a7e9600-b85c-11e9-9c42-e2a0f4fe00ff.png)

Hi，I want to get the all the classes from the folder which name is "App".I use the class File to get all the files of the folder.but when I use File::of or other function just like is_file,is dir,all failed.

then I use the protocols "php","file","res", I can not get the filenames or check it exit. But file_get_contents can get the content of the file.

How can I get file lists and check folder

thank you

**Comment by dim-s** [comment]
You need to add jphp-zend-ext for supporting functions like is_file, dir, etc.

Also it's possible to list files via the `fs` util class:

```php
use php\lib\fs;

fs::scan('/path/to/dir', ["excludeDirs" => true]);
```
see more methods here: https://github.com/jphp-group/jphp/blob/master/jphp-runtime/api-docs/classes/php/lib/fs.md

**Comment by xavieryang007** [comment]
thank you @dim-s

**Comment by xavieryang007** [comment]
![image](https://user-images.githubusercontent.com/6174650/62522061-78d4dd00-b863-11e9-8b4f-a36dd9b2e8b2.png)
Hi . it is still failed

**Comment by xavieryang007** [comment]
the folder will be add into the jar with index.php.   

```
use php\lib\fs;

$files = fs::scan('/path/to/dir', ["excludeDirs" => true]);
```
this can get the current files without the jar.

the "App" folder will build into the jar in the end.
