### ISSUE TITLE
does is support the pdo/pdo_mysql and phpredis ?

### ISSUE THREAD

**Issue by Jamlee** [jphp-group/jphp#324]
pdo and php redis is  heavy dependency for someone. could you can consider to support it ?

**Comment by BurakDev** [comment]
Use https://github.com/jphp-group/jphp/tree/master/exts/jphp-sql-ext/api-docs, there is no PDO usage possible. Redis require an implementation of Java redis library as jphp extension package.

**Comment by Jamlee** [comment]
There are some php program based on [thinkphp](https://github.com/top-think/think) need to be promote.  Many business logic is wrote by  php. So i want to migrate it to JVM platform, or cloud you give some advice  to me?

**Comment by xavieryang007** [comment]
I has write a ext for redis pool
