### ISSUE TITLE
System::osVersion() Error ?

### ISSUE THREAD

**Issue by xywf221** [jphp-group/jphp#325]
I want to get the system version, but it prints out the system name, but I can get it through other functions. Here is my code。
```php
<?php

use php\lang\System;
var_dump(System::osVersion());
var_dump(System::osName());
var_dump(System::getProperty("os.version"));
```
output :
```
string(5) "Linux"
string(5) "Linux"
string(21) "4.4.0-18362-Microsoft"
```
jppm version:
```
--> version: 0.4.2
--> jphp: 1.0.3
--> java: 11.0.5 (amd64)
```

**Comment by nstdio** [comment]
Thanks for reporting the issue. The `System::osVersion()` and `System::osName()` methods both are relay on the same system property: `os.name`.
