### ISSUE TITLE
what about OSv support?

### ISSUE THREAD

**Issue by cypa** [jphp-group/jphp#335]
see subject
http://osv.io/

**Comment by dim-s** [comment]
> OSv supports many managed language runtimes including unmodified JVM

Most likely, the JPHP will work on OSv.

**Comment by cypa** [comment]
and wordpress would not make it on JPHP?08.02.2020, 13:31, "Dmitriy Zayceff" <notifications@github.com>:
OSv supports many managed language runtimes including unmodified JVM

Most likely, the JPHP will work on OSv.

**Comment by dim-s** [comment]
No, jphp doesn't support wordpress and other php CMS.
