### ISSUE TITLE
RFC: numeric_literal_separator

### ISSUE THREAD

**Issue by dim-s** [jphp-group/jphp#338]
https://wiki.php.net/rfc/numeric_literal_separator

**Comment by nstdio** [comment]
Tests:

- https://github.com/php/php-src/blob/master/Zend/tests/numeric_literal_separator_001.phpt
- https://github.com/php/php-src/blob/master/Zend/tests/numeric_literal_separator_002.phpt
- https://github.com/php/php-src/blob/master/Zend/tests/numeric_literal_separator_003.phpt
- https://github.com/php/php-src/blob/master/Zend/tests/numeric_literal_separator_004.phpt
- https://github.com/php/php-src/blob/master/Zend/tests/numeric_literal_separator_005.phpt
- https://github.com/php/php-src/blob/master/Zend/tests/numeric_literal_separator_006.phpt
- https://github.com/php/php-src/blob/master/Zend/tests/numeric_literal_separator_007.phpt
- https://github.com/php/php-src/blob/master/Zend/tests/numeric_literal_separator_008.phpt
- https://github.com/php/php-src/blob/master/Zend/tests/numeric_literal_separator_009.phpt
