### ISSUE TITLE
Cannot define static closures

### ISSUE THREAD

**Issue by danog** [jphp-group/jphp#367]
Static closures cannot be defined:

```php
$a = static function() {};
```

Result:
```
Fatal error: Uncaught ParseError: Syntax error, unexpected '$a' in res://c.php on line 2, position 1
```

(The error is especially weird, since it throws at `$a`, not at `static`. If `$a =` is removed, the same error is thrown at `static`).

**Comment by dim-s** [comment]
Hmm, I did not know about this feature. Arrow functions support this.
