### ISSUE TITLE
Cannot conditionally define classes

### ISSUE THREAD

**Issue by danog** [jphp-group/jphp#368]
I'm not sure if this can be done at all in JPHP, but I cannot conditionally define classes (behaviour usually used for polyfilling missing feaures).

**Comment by dim-s** [comment]
This function cannot be correctly implemented due to the jphp engine loads classes of php file when it loads, not at runtime.

**Comment by danog** [comment]
No biggie, I can always try to detect jphp and avoid polyfilling

**Comment by dim-s** [comment]
You can try `if` + `include`, for example:

```php
if (JPHP) {
   include "jphp_class.php"
} else {
   include "php_class.php";
}
```

**Comment by danog** [comment]
Could it be possible to load both classes on startup, and then select the one to use during runtime?
