### ISSUE TITLE
Missing support for typed properties (PHP 7.4)

### ISSUE THREAD

**Issue by danog** [jphp-group/jphp#372]
https://wiki.php.net/rfc/typed_properties_v2

**Comment by dim-s** [comment]
Update jphp-core to 1.2.0 to support typed props.

**Comment by dim-s** [comment]
`jppm update jphp-core`

**Comment by danog** [comment]
Hmm `jppm update` does not seem to do the trick, anonymous classes still won't be loaded.
Maybe dev snapshots of the libs should be pulled, would you add some docs describing the contents of the jppm config file?

**Comment by dim-s** [comment]
`jppm deps` shows all dep versions. `jphp-core` and `jphp-runtime` should be `1.2.0` or higher.

**Comment by dim-s** [comment]
Also in `package.php.yml` you can specify version for `jphp-core` dependency:

```yml
deps:
  jphp-core: ^1.2.0
```

**Comment by danog** [comment]
Thanks!
