### ISSUE TITLE
Missing cryptographically secure RNG functions

### ISSUE THREAD

**Issue by danog** [jphp-group/jphp#397]
The quite important PHP 7 CSPRNG functions are missing: https://www.php.net/manual/en/ref.csprng.php

**Comment by dim-s** [comment]
It's can be implemented through the `java.security.SecureRandom` class.

**Comment by danog** [comment]
Actually, those are already implemented in the zend ext, but for some reason jppm pulls an outdated version.
Compiling the extension locally works just fine, providing the CSPRNG functions.

**Comment by dim-s** [comment]
I updated the extension, it should work now. To update the version do not forget to run `jppm update`
